version: '3.8'

services:
  web:
    user: "${UID}"
    build: 
      context: ./app
      args:
        UID: ${UID}

    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./app:/src/app
      - static:/vol/web
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    

  db:
    image: mariadb:10.9.6
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    command:
      - "--character-set-server=utf8mb4"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}

  celery:
    user: "${UID}"
    build:
      context: ./app
      args:
        UID: ${UID}
    volumes:
      - ./app:/src/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    container_name: mammalbase_celery
    command:
      - watchfiles
      - --filter
      - python
      - celery -A config --workdir=. worker -l INFO --concurrency=1
  
  celery-beat:
    user: "${UID}"
    build:
      context: ./app
      args:
        UID: ${UID}
    volumes:
      - ./app:/src/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    container_name: mammalbase_celery_beat
    command:
      - watchfiles
      - --filter
      - python
      - celery -A config --workdir=. beat -l INFO

  redis:
    image: redis:alpine
    expose:
      - "6379"
    container_name: mammalbase_redis

volumes:
  db: null
  static: null
