"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import environ, path
from datetime import timedelta
from pathlib import Path

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get('SECRET_KEY', 'development_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(environ.get('DEBUG', 0)))



""" PATHS """

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = environ.get('STATIC_ROOT', path.join(BASE_DIR, 'static'))

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = environ.get('MEDIA_ROOT', path.join(BASE_DIR, 'media'))



# RECODE extraction hardening defaults
RECODE_ASSETS_DIR = Path(environ.get('RECODE_ASSETS_DIR', str(BASE_DIR / 'var' / 'recode_assets')))
RECODE_ENABLE_LLM_BACKEND = bool(int(environ.get('RECODE_ENABLE_LLM_BACKEND', 0)))
RECODE_MAX_PDF_MB = int(environ.get('RECODE_MAX_PDF_MB', 25))
RECODE_TIMEOUT_SECONDS = int(environ.get('RECODE_TIMEOUT_SECONDS', 120))
RECODE_ENABLE_OPENAI_BACKEND = bool(int(environ.get('RECODE_ENABLE_OPENAI_BACKEND', 0)))
RECODE_OPENAI_MODEL_PASS1 = environ.get('RECODE_OPENAI_MODEL_PASS1', 'gpt-5-mini')
RECODE_OPENAI_MODEL_PASS2 = environ.get('RECODE_OPENAI_MODEL_PASS2', 'gpt-5-mini')
RECODE_OPENAI_MODEL_CHOICES = (
    'gpt-5.4',
    'gpt-5.2',
    'gpt-5-mini',
    'gpt-4.1',
)
RECODE_OPENAI_TIMEOUT_SECONDS = int(environ.get('RECODE_OPENAI_TIMEOUT_SECONDS', 120))
RECODE_OPENAI_MAX_RETRIES = int(environ.get('RECODE_OPENAI_MAX_RETRIES', 5))
RECODE_OPENAI_MAX_PAGE_CHARS = int(environ.get('RECODE_OPENAI_MAX_PAGE_CHARS', 12000))
RECODE_OPENAI_PASS1_MAX_ITEMS_PER_BUCKET = int(environ.get('RECODE_OPENAI_PASS1_MAX_ITEMS_PER_BUCKET', 120))
RECODE_OPENAI_PASS1_MAX_ITEM_CHARS = int(environ.get('RECODE_OPENAI_PASS1_MAX_ITEM_CHARS', 2500))
RECODE_OPENAI_PASS1_MAX_TABLE_ITEM_CHARS = int(environ.get('RECODE_OPENAI_PASS1_MAX_TABLE_ITEM_CHARS', 12000))

RECODE_ENABLE_CLAUDE_BACKEND = bool(int(environ.get('RECODE_ENABLE_CLAUDE_BACKEND', 0)))
RECODE_CLAUDE_MODEL_PASS1 = environ.get('RECODE_CLAUDE_MODEL_PASS1', 'claude-3-5-sonnet')
RECODE_CLAUDE_MODEL_PASS2 = environ.get('RECODE_CLAUDE_MODEL_PASS2', 'claude-3-5-sonnet')
RECODE_CLAUDE_TIMEOUT_SECONDS = int(environ.get('RECODE_CLAUDE_TIMEOUT_SECONDS', 120))


""" Adresses and protocols """
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http" if DEBUG else "https"

ALLOWED_HOSTS = []
ALLOWED_HOSTS_ENV = environ.get('ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))

CSRF_TRUSTED_ORIGINS = []
TRUSTED_ORIGINS_ENV = environ.get('TRUSTED_ORIGINS')
if TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS.extend(TRUSTED_ORIGINS_ENV.split(','))

SITE_DOMAIN = environ.get('SITE_DOMAIN', 'mammalbase.net')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',

#    'django_userforeignkey',
    'django_select2',

    'django_filters',

    "django_celery_results",
    "celery_progress",

    # https://django-simple-history.readthedocs.io/
    'simple_history',

    'main.apps.MainConfig',
    'mb.apps.MbConfig',
    'tdwg.apps.TdwgConfig',

    'imports.apps.ImportsConfig',
    'recode_extraction.apps.RecodeExtractionConfig',
    'itis',
    'exports.apps.ExportsConfig',
    'matchtools',
    'tgn',
    'wdpa',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.orcid',

#    'django_extensions', #for Jupyter and Scripts
#    'crispy_forms',
#    'users.apps.UsersConfig',
#    'rest_framework',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'middleware.current_user.CurrentUserMiddleware',
    # https://django-simple-history.readthedocs.io/
    'simple_history.middleware.HistoryRequestMiddleware',
]

# All URL configuration can be found on urls subpackage located at /app/urls
ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',

                # `allauth` needs this from django
                'django.template.context_processors.request',

                # for using the default auth backend in order to use the admin application.
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ORCID Allauth Settings
# Operational note: ensure allauth socialaccount migrations are applied in MySQL.
# Missing columns (e.g., socialaccount_socialapp.provider_id) indicate skipped migrations.
# https://django-allauth.readthedocs.io/en/latest/installation.html

AUTHENTICATION_BACKENDS = [
     # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
     'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
     'orcid': {
         'BASE_DOMAIN': 'orcid.org',
         'MEMBER_API': False,
         'APP': {
             'client_id': environ.get("ORCID_CLIENT_ID", ''),
             'secret': environ.get("ORCID_SECRET", ''),
             'key': '',
        }
    }
}

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': environ.get('DB_HOST'),
        'NAME': environ.get('DB_NAME'),
        'USER': environ.get('DB_USER'),
        'PASSWORD': environ.get('DB_PASS'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': None,
        'CONN_HEALTH_CHECKS': True,
    }
}
# sq lite for testing
if 'test' in environ.get('DJANGO_SETTINGS_MODULE', ''):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3'
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Helsinki'
USE_I18N = True
USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'select2': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


SELECT2_CACHE_BACKEND = 'select2'
ITIS_CACHE = environ.get("ITIS_CACHE", "/vol/web/static/itis_cache")


# Celery configuration
CELERY_BROKER_URL = environ.get("CELERY_BROKER", "redis://redis:6379")
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULE = {
    "update_db_from_itis" : {
        "task": "mb.tasks.update_db_from_itis",
        "schedule": timedelta(days = 30),
        "args":(),
        "options": {
        }
    },

    "update_dqs_in_db" : {
        "task": "mb.tasks.update_dqs",
        "schedule": timedelta(days = 30),
        "args":(),
        "options": {
        }
    }
}


# Email configuration
EMAIL_HOST_PASSWORD = environ.get('EMAIL_HOST_PASSWORD')
EMAIL_BACKEND = environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = environ.get('EMAIL_HOST')
EMAIL_HOST_USER = environ.get('EMAIL_HOST_USER')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = environ.get('DEFAULT_FROM_EMAIL')



if DEBUG:

    # Django Debug Toolbar
    # https://django-debug-toolbar.readthedocs.io/

    import socket
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[:-1] + '1' for ip in ips] + ['127.0.0.1', '10.0.2.2']

    INSTALLED_APPS += [ 'debug_toolbar' ]
    MIDDLEWARE += [ 'debug_toolbar.middleware.DebugToolbarMiddleware' ]

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
    ]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'tgn': {  # specific app/module logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
