# Generated by Django 3.2.19 on 2023-05-26 10:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/export_files'), upload_to='')),
            ],
        ),
    ]
