# Generated by Django 3.2.19 on 2023-05-26 10:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage()),
        ),
    ]
