# Generated by Django 5.2.2 on 2026-01-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_auto_20230613_1348"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
