# Generated by Django 5.2.2 on 2026-01-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0003_alter_exportfile_created_by_and_more"),
        ("exports", "0003_alter_historicalexportfile_options_and_more"),
    ]

    operations = []
