# Generated by Django 5.2.9 on 2026-01-12 13:05

import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_merge_0003_alter_exportfile_created_by_and_more_0003_alter_historicalexportfile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportfile',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalexportfile',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalexportfile',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
