# Generated by Django 3.0.3 on 2020-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongNames',
            fields=[
                ('tsn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('completename', models.CharField(max_length=200)),
            ],
        ),
    ]
