# Generated by Django 3.0.3 on 2020-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomicUnits',
            fields=[
                ('tsn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('completename', models.CharField(max_length=200)),
            ],
        ),
    ]
