# Generated by Django 3.0.3 on 2020-02-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0004_auto_20200226_1730'),
        ('itis', '0002_taxonomicunits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LongNames',
        ),
    ]
