# Generated by Django 3.0.3 on 2020-02-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0003_delete_longnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsn', models.ForeignKey(db_column='tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_synonym', to='itis.TaxonomicUnits')),
                ('tsn_accepted', models.ForeignKey(db_column='tsn_accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_accepted', to='itis.TaxonomicUnits')),
            ],
        ),
    ]
