# Generated by Django 3.0.3 on 2020-05-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0004_synonymlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomicunits',
            name='common_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxonomicunits',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxonomicunits',
            name='hierarchy_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxonomicunits',
            name='tsn_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
