# Generated by Django 3.0.3 on 2020-05-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0005_auto_20200527_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymlinks',
            name='tsn_accepted_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
