# Generated by Django 3.0.3 on 2020-05-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0007_auto_20200530_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomicunits',
            name='common_names',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomicunits',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
