# Generated by Django 3.0.3 on 2020-06-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0008_auto_20200530_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomicunits',
            options={'ordering': ['hierarchy_string']},
        ),
    ]
