# Generated by Django 5.2.11 on 2026-03-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recode_extraction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceextractionrun",
            name="extracted_text_package",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
