# Generated by Django 5.2.11 on 2026-03-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recode_extraction", "0002_sourceextractionrun_extracted_text_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceextractionrun",
            name="unmapped_traits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ExtractedAssertionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_taxon", models.CharField(max_length=250)),
                ("trait_name", models.CharField(max_length=250)),
                ("value_raw", models.CharField(max_length=250)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("context", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0)),
                ("evidence_start", models.IntegerField(blank=True, null=True)),
                ("evidence_end", models.IntegerField(blank=True, null=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("mapped_trait_id", models.CharField(blank=True, max_length=100)),
                ("ets_payload", models.JSONField(blank=True, default=dict)),
                ("ets_persisted", models.BooleanField(default=False)),
                ("unmapped_reason", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="recode_extraction.sourceextractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("taxon", "Taxon"),
                            ("trait", "Trait"),
                            ("value", "Value"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("start_offset", models.IntegerField(blank=True, null=True)),
                ("end_offset", models.IntegerField(blank=True, null=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="recode_extraction.sourceextractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
