# Generated by Django 5.2.11 on 2026-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recode_extraction", "0003_sourceextractionrun_unmapped_traits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceextractionrun",
            name="current_stage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sourceextractionrun",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
