# Generated by Django 5.2.11 on 2026-03-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recode_extraction", "0004_sourceextractionrun_current_stage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="edited_unit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="edited_value",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recode_reviewed_assertions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="reviewer_note",
            field=models.TextField(blank=True),
        ),
    ]
