# Generated by Django 5.2.11 on 2026-03-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recode_extraction", "0005_extractedassertionmodel_edited_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=64)),
                (
                    "drawn_from_token_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="extractedassertionmodel",
            name="review_status",
        ),
        migrations.RemoveField(
            model_name="extractedentity",
            name="end_offset",
        ),
        migrations.RemoveField(
            model_name="extractedentity",
            name="start_offset",
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="coord_text",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="count_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="date_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="imported_source_measurement_value_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="locality_text",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="lstage_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="ref_text",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="sex_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("imported", "Imported"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="token_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="extractedassertionmodel",
            name="unit_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="end_offset_utf16",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="span_external_id",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="start_offset_utf16",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="token_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="extractedentity",
            name="confidence",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="extractedentity",
            name="entity_type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="sourceextractionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedentity",
            constraint=models.UniqueConstraint(
                fields=("extraction_run", "span_external_id"),
                name="uniq_entity_per_run_span_external_id",
            ),
        ),
        migrations.AddField(
            model_name="extractedrelation",
            name="extraction_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="recode_extraction.sourceextractionrun",
            ),
        ),
        migrations.AddField(
            model_name="extractedrelation",
            name="head_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_relations",
                to="recode_extraction.extractedentity",
            ),
        ),
        migrations.AddField(
            model_name="extractedrelation",
            name="tail_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_relations",
                to="recode_extraction.extractedentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedrelation",
            constraint=models.UniqueConstraint(
                fields=(
                    "extraction_run",
                    "relation_type",
                    "head_entity",
                    "tail_entity",
                    "drawn_from_token_id",
                ),
                name="uniq_relation_per_run_endpoints",
            ),
        ),
    ]
