# Generated by Django 3.0.3 on 2020-02-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0002_taxonomicunits'),
        ('mb', '0003_historicalreferencerelation_referencerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='tsn',
            field=models.ForeignKey(db_column='tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='itis.TaxonomicUnits'),
        ),
        migrations.AlterField(
            model_name='historicalfooditem',
            name='tsn',
            field=models.ForeignKey(blank=True, db_column='tsn', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='itis.TaxonomicUnits'),
        ),
    ]
