# Generated by Django 3.0.3 on 2020-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0004_auto_20200226_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the Title of the Master Reference', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the Title of the Master Reference', max_length=300, null=True),
        ),
    ]
