# Generated by Django 3.0.3 on 2020-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0005_auto_20200227_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcereference',
            name='doi',
            field=models.URLField(blank=True, help_text='Enter a valid DOI URL for the Source Reference', null=True),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='doi',
            field=models.URLField(blank=True, help_text='Enter a valid DOI URL for the Source Reference', null=True),
        ),
    ]
