# Generated by Django 3.0.3 on 2020-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0006_auto_20200227_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsourcereference',
            name='citation',
            field=models.CharField(help_text='Enter the Citation of the Source Reference', max_length=450),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='citation',
            field=models.CharField(help_text='Enter the Citation of the Source Reference', max_length=450),
        ),
    ]
