# Generated by Django 3.0.3 on 2020-03-10 19:19

from django.db import migrations, models
import mb.models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0008_auto_20200310_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=50, null=True, validators=[mb.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=50, null=True, validators=[mb.models.validate_doi]),
        ),
    ]
