# Generated by Django 3.0.3 on 2020-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0009_auto_20200310_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityclass',
            name='name',
            field=models.CharField(help_text='Enter the Name of the Entity Class', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalentityclass',
            name='name',
            field=models.CharField(help_text='Enter the Name of the Entity Class', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsourcereference',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created - Not verified'), (2, 'Verified - Accepted'), (3, 'Verified - Rejected')], default=1, help_text='Status of the Std. Reference'),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created - Not verified'), (2, 'Verified - Accepted'), (3, 'Verified - Rejected')], default=1, help_text='Status of the Std. Reference'),
        ),
    ]
