# Generated by Django 3.0.3 on 2020-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0011_historicalmasterattribute_masterattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterattribute',
            name='remarks',
            field=models.TextField(help_text='Enter remarks for the Master Attribute', max_length=500),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='remarks',
            field=models.TextField(help_text='Enter remarks for the Master Attribute', max_length=500),
        ),
    ]
