# Generated by Django 3.0.3 on 2020-03-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20200324_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Master Attribute', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Master Attribute', max_length=500, null=True),
        ),
    ]
