# Generated by Django 3.0.3 on 2020-03-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0014_auto_20200325_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrelation',
            name='data_status',
            field=models.ForeignKey(limit_choices_to={'master_attribute__name': 'Verification'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datastatusentityrelation', to='mb.MasterChoiceSetOption'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='relation_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationstatusentityrelation', to='mb.MasterChoiceSetOption'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Entity Relation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalentityrelation',
            name='data_status',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'master_attribute__name': 'Verification'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.MasterChoiceSetOption'),
        ),
        migrations.AddField(
            model_name='historicalentityrelation',
            name='relation_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.MasterChoiceSetOption'),
        ),
        migrations.AddField(
            model_name='historicalentityrelation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Entity Relation', max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelation',
            unique_together={('source_entity', 'master_entity', 'relation')},
        ),
    ]
