# Generated by Django 3.0.3 on 2020-04-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0018_attributerelation_historicalattributerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsourcechoicesetoption',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description for the Source Choice Set Option', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsourcechoicesetoption',
            name='name',
            field=models.CharField(help_text='Enter the Source Choice Set Option', max_length=250),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoption',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description for the Source Choice Set Option', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoption',
            name='name',
            field=models.CharField(help_text='Enter the Source Choice Set Option', max_length=250),
        ),
        migrations.CreateModel(
            name='SourceChoiceSetOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_sourcechoicesetoptionvalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_sourcechoicesetoptionvalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_choiceset_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceChoiceSetOption')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceEntity')),
            ],
            options={
                'ordering': ['source_entity__name', 'source_choiceset_option__display_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSourceChoiceSetOptionValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_choiceset_option', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceChoiceSetOption')),
                ('source_entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceEntity')),
            ],
            options={
                'verbose_name': 'historical source choice set option value',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
