# Generated by Django 3.0.3 on 2020-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0019_auto_20200408_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourceattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Numerical variable'), (2, 'Categorical variable')], default=1, help_text='Select the type of the Attribute'),
        ),
        migrations.AddField(
            model_name='sourceattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Numerical variable'), (2, 'Categorical variable')], default=1, help_text='Select the type of the Attribute'),
        ),
        migrations.AlterField(
            model_name='historicalsourceattribute',
            name='name',
            field=models.CharField(help_text='Enter the Name of the Attribute', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalsourceattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Attribute', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sourceattribute',
            name='name',
            field=models.CharField(help_text='Enter the Name of the Attribute', max_length=250),
        ),
        migrations.AlterField(
            model_name='sourceattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Attribute', max_length=500, null=True),
        ),
    ]
