# Generated by Django 3.0.3 on 2020-04-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0020_auto_20200419_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMeasurementValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('n_total', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of specimens measured.', null=True)),
                ('n_unknown', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of unknown gender specimens measured.', null=True)),
                ('n_male', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of male specimens measured.', null=True)),
                ('n_female', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of female specimens measured.', null=True)),
                ('minimum', models.DecimalField(decimal_places=10, help_text='Minimum measurement value reported.', max_digits=19)),
                ('maximum', models.DecimalField(decimal_places=10, help_text='Maximum measurement value reported.', max_digits=19)),
                ('mean', models.DecimalField(decimal_places=10, help_text='Mean of measurement values reported.', max_digits=19)),
                ('std', models.DecimalField(decimal_places=10, help_text='Standard deviation of measurement values reported.', max_digits=19)),
                ('unit', models.CharField(help_text='Measurement unit reported.', max_length=250)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_sourcemeasurementvalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_sourcemeasurementvalue', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceAttribute')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceEntity')),
            ],
            options={
                'ordering': ['source_attribute__name', '-n_total'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSourceMeasurementValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('n_total', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of specimens measured.', null=True)),
                ('n_unknown', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of unknown gender specimens measured.', null=True)),
                ('n_male', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of male specimens measured.', null=True)),
                ('n_female', models.PositiveSmallIntegerField(blank=True, default=0, help_text='n for total number of female specimens measured.', null=True)),
                ('minimum', models.DecimalField(decimal_places=10, help_text='Minimum measurement value reported.', max_digits=19)),
                ('maximum', models.DecimalField(decimal_places=10, help_text='Maximum measurement value reported.', max_digits=19)),
                ('mean', models.DecimalField(decimal_places=10, help_text='Mean of measurement values reported.', max_digits=19)),
                ('std', models.DecimalField(decimal_places=10, help_text='Standard deviation of measurement values reported.', max_digits=19)),
                ('unit', models.CharField(help_text='Measurement unit reported.', max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_attribute', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceAttribute')),
                ('source_entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceEntity')),
            ],
            options={
                'verbose_name': 'historical source measurement value',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
