# Generated by Django 3.0.3 on 2020-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0021_historicalsourcemeasurementvalue_sourcemeasurementvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='std',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, help_text='Standard deviation of measurement values reported.', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='std',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, help_text='Standard deviation of measurement values reported.', max_digits=19, null=True),
        ),
    ]
