# Generated by Django 3.0.3 on 2020-05-08 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0023_choicesetoptionrelation_historicalchoicesetoptionrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the name of the Master Unit', max_length=25)),
                ('print_name', models.CharField(help_text='Enter the Print value of the name of a Master Unit', max_length=25)),
                ('quantity_type', models.CharField(help_text='Enter the Quantity type of the Master Unit', max_length=25)),
                ('unit_value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('remarks', models.TextField(blank=True, help_text='Enter remarks for the Master Unit', max_length=500, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_masterunit', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_masterunit', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'ordering': ['quantity_type', 'unit_value'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMasterUnit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the name of the Master Unit', max_length=25)),
                ('print_name', models.CharField(help_text='Enter the Print value of the name of a Master Unit', max_length=25)),
                ('quantity_type', models.CharField(help_text='Enter the Quantity type of the Master Unit', max_length=25)),
                ('unit_value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('remarks', models.TextField(blank=True, help_text='Enter remarks for the Master Unit', max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'verbose_name': 'historical master unit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
