# Generated by Django 3.0.3 on 2020-05-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0024_historicalmasterunit_masterunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterattribute',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.MasterUnit'),
        ),
        migrations.AddField(
            model_name='masterattribute',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.MasterUnit'),
        ),
    ]
