# Generated by Django 3.0.3 on 2020-05-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0026_historicalsourceunit_sourceunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='source_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceUnit'),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='source_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.SourceUnit'),
        ),
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='unit',
            field=models.CharField(help_text='Measurement unit reported.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='unit',
            field=models.CharField(help_text='Measurement unit reported.', max_length=250, null=True),
        ),
    ]
