# Generated by Django 3.0.3 on 2020-05-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0027_auto_20200510_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='source_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.SourceUnit'),
        ),
    ]
