# Generated by Django 3.0.3 on 2020-05-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0032_historicalsourcelocation_sourcelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_dietset', to='mb.SourceLocation'),
        ),
        migrations.AlterField(
            model_name='historicaldietset',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceLocation'),
        ),
    ]
