# Generated by Django 3.0.3 on 2020-05-24 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0033_auto_20200523_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietset',
            options={'ordering': ['taxon__name', 'reference']},
        ),
        migrations.AddField(
            model_name='dietset',
            name='gender',
            field=models.ForeignKey(limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.ChoiceValue'),
        ),
        migrations.AddField(
            model_name='dietset',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sample Size'),
        ),
        migrations.AddField(
            model_name='dietset',
            name='study_time',
            field=models.CharField(help_text='Enter the time when this study was performed.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.ChoiceValue'),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sample Size'),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='study_time',
            field=models.CharField(help_text='Enter the time when this study was performed.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dietset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_dietset', to='mb.SourceLocation'),
        ),
        migrations.AlterField(
            model_name='dietset',
            name='taxon',
            field=models.ForeignKey(limit_choices_to=models.Q(('entity__name', 'Genus'), ('entity__name', 'Species'), ('entity__name', 'Subspecies'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='taxon_dietset', to='mb.SourceEntity'),
        ),
        migrations.AlterField(
            model_name='historicaldietset',
            name='taxon',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('entity__name', 'Genus'), ('entity__name', 'Species'), ('entity__name', 'Subspecies'), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceEntity'),
        ),
        migrations.AlterUniqueTogether(
            name='dietset',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the Time Period', max_length=50)),
                ('time_in_months', models.PositiveSmallIntegerField(default=12, help_text='Enter an estimate of Time Period in months.')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_timeperiod', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_timeperiod', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceReference')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('reference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SourceMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the method described in the Reference', max_length=250)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_sourcemethod', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_sourcemethod', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceReference')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('reference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalTimePeriod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the Time Period', max_length=50)),
                ('time_in_months', models.PositiveSmallIntegerField(default=12, help_text='Enter an estimate of Time Period in months.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceReference')),
            ],
            options={
                'verbose_name': 'historical time period',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSourceMethod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('name', models.CharField(help_text='Enter the method described in the Reference', max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceReference')),
            ],
            options={
                'verbose_name': 'historical source method',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='dietset',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_dietset', to='mb.SourceMethod'),
        ),
        migrations.AddField(
            model_name='dietset',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_period_dietset', to='mb.TimePeriod'),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceMethod'),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='time_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.TimePeriod'),
        ),
    ]
