# Generated by Django 3.0.3 on 2020-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0034_auto_20200525_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietset',
            name='cited_reference',
            field=models.CharField(help_text='Enter the original reference, if not this study.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='cited_reference',
            field=models.CharField(help_text='Enter the original reference, if not this study.', max_length=250, null=True),
        ),
    ]
