# Generated by Django 3.0.3 on 2020-05-25 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0037_auto_20200525_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietsetitem',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='List order on Diet Set'),
        ),
        migrations.AddField(
            model_name='dietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='historicaldietsetitem',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='List order on Diet Set'),
        ),
        migrations.AddField(
            model_name='historicaldietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
