# Generated by Django 3.0.3 on 2020-05-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0038_auto_20200525_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietsetitem',
            options={'ordering': ['list_order', '-percentage']},
        ),
    ]
