# Generated by Django 3.0.3 on 2020-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0041_auto_20200609_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproximateanalysisitem',
            name='remarks',
            field=models.CharField(blank=True, help_text='Enter remarks.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalproximateanalysisitem',
            name='transformation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proximateanalysisitem',
            name='remarks',
            field=models.CharField(blank=True, help_text='Enter remarks.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proximateanalysisitem',
            name='transformation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
