# Generated by Django 3.0.3 on 2020-06-12 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0042_auto_20200612_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='ash_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='ash_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='cf_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='cf_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='cp_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='cp_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='dm_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='ee_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='ee_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='moisture_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='nfe_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='nfe_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='sample_size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Sample size', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='total_carbohydrates_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='ash_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='ash_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='cf_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='cf_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='cp_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='cp_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='dm_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='ee_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='ee_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='moisture_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='nfe_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='nfe_std',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='sample_size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Sample size', null=True),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='total_carbohydrates_reported',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
