# Generated by Django 3.0.3 on 2020-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0043_auto_20200613_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProximateAnalysisTable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('taxon_name', models.CharField(max_length=200)),
                ('hierarchy', models.CharField(blank=True, max_length=400, null=True)),
                ('tsn_hierarchy', models.CharField(blank=True, max_length=200, null=True)),
                ('part', models.CharField(max_length=200)),
                ('cp_std', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('ee_std', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('cf_std', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('ash_std', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('nfe_std', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('n_taxa', models.PositiveSmallIntegerField()),
                ('n_reference', models.PositiveSmallIntegerField()),
                ('n_analysis', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'mb_view_pa_table',
                'ordering': ['part', 'tsn_hierarchy'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='citation',
            field=models.CharField(help_text='Enter the Citation of the Standard Reference', max_length=400),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='container_title',
            field=models.CharField(blank=True, help_text='Enter the Container Title of the Standard Reference', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='first_author',
            field=models.CharField(blank=True, help_text='Enter the name of the first author of the Standard Reference', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='issue',
            field=models.CharField(blank=True, help_text='Enter the Issue of the Standard Reference', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='page',
            field=models.CharField(blank=True, help_text='Enter the Page(s) of the Standard Reference', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the Title of the Standard Reference', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='type',
            field=models.CharField(blank=True, help_text='Enter the Type of the Standard Reference', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='citation',
            field=models.CharField(help_text='Enter the Citation of the Standard Reference', max_length=400),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='container_title',
            field=models.CharField(blank=True, help_text='Enter the Container Title of the Standard Reference', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='first_author',
            field=models.CharField(blank=True, help_text='Enter the name of the first author of the Standard Reference', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='issue',
            field=models.CharField(blank=True, help_text='Enter the Issue of the Standard Reference', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='page',
            field=models.CharField(blank=True, help_text='Enter the Page(s) of the Standard Reference', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the Title of the Standard Reference', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='type',
            field=models.CharField(blank=True, help_text='Enter the Type of the Standard Reference', max_length=25, null=True),
        ),
    ]
