# Generated by Django 3.0.3 on 2020-08-18 10:37

from django.db import migrations, models
import mb.models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0044_auto_20200818_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=100, null=True, validators=[mb.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=100, null=True, validators=[mb.models.validate_doi]),
        ),
    ]
