# Generated by Django 3.0.3 on 2020-08-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0045_auto_20200818_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='source_location',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceLocation'),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='source_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.SourceLocation'),
        ),
        migrations.AlterField(
            model_name='historicalsourceattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Specified'), (1, 'Numerical variable'), (2, 'Categorical variable')], default=3, help_text='Select the type of the Attribute'),
        ),
        migrations.AlterField(
            model_name='sourceattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Specified'), (1, 'Numerical variable'), (2, 'Categorical variable')], default=3, help_text='Select the type of the Attribute'),
        ),
    ]
