# Generated by Django 3.0.3 on 2020-09-07 13:33

from django.db import migrations, models
import mb.models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0047_auto_20200902_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsourcereference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=100, null=True, validators=[mb.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=100, null=True, validators=[mb.models.validate_doi]),
        ),
    ]
