# Generated by Django 3.0.3 on 2020-09-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0048_auto_20200907_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterreference',
            name='uri',
            field=models.URLField(blank=True, help_text='Enter the Uniform Resource Identifier link', null=True),
        ),
        migrations.AddField(
            model_name='masterreference',
            name='uri',
            field=models.URLField(blank=True, help_text='Enter the Uniform Resource Identifier link', null=True),
        ),
    ]
