# Generated by Django 3.0.3 on 2020-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0050_auto_20200916_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterchoicesetoption',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description for the Master Choice Set Option', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='masterchoicesetoption',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description for the Master Choice Set Option', max_length=1500, null=True),
        ),
    ]
