# Generated by Django 3.0.3 on 2020-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0051_auto_20200916_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMasterTraitValue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('master_entity_name', models.CharField(max_length=200)),
                ('master_attribute_name', models.CharField(max_length=200)),
                ('traits_references', models.CharField(blank=True, max_length=400, null=True)),
                ('assigned_values', models.CharField(blank=True, max_length=400, null=True)),
                ('n_distinct_value', models.PositiveSmallIntegerField()),
                ('n_value', models.PositiveSmallIntegerField()),
                ('n_supporting_value', models.PositiveSmallIntegerField()),
                ('trait_values', models.CharField(blank=True, max_length=400, null=True)),
                ('trait_selected', models.CharField(blank=True, max_length=400, null=True)),
                ('trait_references', models.CharField(blank=True, max_length=400, null=True)),
                ('value_percentage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'mb_view_master_trait_values',
                'ordering': ['id', 'master_attribute_name'],
                'managed': False,
            },
        ),
    ]
