# Generated by Django 3.0.3 on 2020-10-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis', '0009_auto_20200609_1733'),
        ('mb', '0052_viewmastertraitvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewproximateanalysistable',
            options={'managed': False, 'ordering': ['part', 'tsn__hierarchy']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pa_tsn',
            field=models.ForeignKey(blank=True, db_column='pa_tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_pa', to='itis.TaxonomicUnits'),
        ),
        migrations.AddField(
            model_name='historicalfooditem',
            name='pa_tsn',
            field=models.ForeignKey(blank=True, db_column='pa_tsn', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='itis.TaxonomicUnits'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='tsn',
            field=models.ForeignKey(blank=True, db_column='tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_food', to='itis.TaxonomicUnits'),
        ),
    ]
