# Generated by Django 3.2.24 on 2024-04-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomicUnits',
            fields=[
                ('tsn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('kingdom_id', models.PositiveSmallIntegerField(help_text='Kingdom')),
                ('rank_id', models.PositiveSmallIntegerField(help_text='Rank')),
                ('completename', models.CharField(max_length=200)),
                ('hierarchy_string', models.CharField(blank=True, max_length=200, null=True)),
                ('hierarchy', models.CharField(blank=True, max_length=400, null=True)),
                ('common_names', models.CharField(blank=True, max_length=400, null=True)),
                ('tsn_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['hierarchy_string'],
            },
        ),
        migrations.CreateModel(
            name='SynonymLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsn_accepted_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tsn', models.ForeignKey(db_column='tsn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_synonym', to='itis.taxonomicunits')),
                ('tsn_accepted', models.ForeignKey(db_column='tsn_accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsn_accepted', to='itis.taxonomicunits')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonUnitTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_id', models.PositiveSmallIntegerField(help_text='Rank id')),
                ('rank_name', models.CharField(max_length=15)),
                ('dir_parent_rank_id', models.PositiveSmallIntegerField(help_text='Direct Parent Rank')),
                ('req_parent_rank_id', models.PositiveSmallIntegerField(help_text='Required Parent Rank')),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itis.kingdom')),
            ],
            options={
                'unique_together': {('kingdom_id', 'rank_id')},
            },
        ),
    ]
