# Generated by Django 3.2.18 on 2023-05-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdwg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='display_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='sort_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, help_text='The authorship information of the scientific name.', max_length=150, null=True),
        ),
    ]
