# Generated by Django 3.2.25 on 2024-04-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0002_historicalmasterlocationviewobj_masterlocationviewobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlocationviewobj',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='masterlocationviewobj',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HistoricalMasterLocationViewObj',
        ),
        migrations.DeleteModel(
            name='MasterLocationViewObj',
        ),
    ]
