# Generated by Django 3.2.12 on 2022-06-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0003_historicalsourcestatistic_sourcestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text='Enter the original reference, if not this study.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.choicevalue'),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Source Measurement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='source_statistic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcestatistic'),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text='Enter the original reference, if not this study.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.choicevalue'),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Source Measurement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='source_statistic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.sourcestatistic'),
        ),
    ]
