# Generated by Django 3.2.12 on 2022-09-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0005_auto_20220615_1608'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewmastertraitvalue',
            table='mb_view_master_trait_values',
        ),
    ]
