# Generated by Django 3.2.15 on 2022-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0006_alter_viewmastertraitvalue_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text='Enter the original reference, if not this study.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text='Enter the original reference, if not this study.', max_length=1000, null=True),
        ),
    ]
