# Generated by Django 3.2.15 on 2023-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0007_auto_20221214_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietset',
            name='cited_reference',
            field=models.CharField(blank=True, help_text="Enter the original reference, if not this study. If original, enter 'Original study'.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldietset',
            name='cited_reference',
            field=models.CharField(blank=True, help_text="Enter the original reference, if not this study. If original, enter 'Original study'.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text="Enter the original reference, if not this study. If original, enter 'Original study'.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='cited_reference',
            field=models.CharField(blank=True, help_text="Enter the original reference, if not this study. If original, enter 'Original study'.", max_length=1000, null=True),
        ),
    ]
