# Generated by Django 3.2.19 on 2023-06-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20230523_1304'),
        ('mb', '0012_auto_20230602_2148'),
    ]

    operations = [
    ]
