# Generated by Django 3.2.23 on 2024-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20240208_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterchoicesetoption',
            name='source_choiceset_option',
            field=models.ManyToManyField(through='mb.ChoiceSetOptionRelation', to='mb.SourceChoiceSetOption'),
        ),
        migrations.AddField(
            model_name='sourcechoicesetoption',
            name='master_choiceset_option',
            field=models.ManyToManyField(through='mb.ChoiceSetOptionRelation', to='mb.MasterChoiceSetOption'),
        ),
    ]
