# Generated by Django 3.2.23 on 2024-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20240213_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterhabitat',
            name='biome_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter the biome code of the Master Habitat', null=True),
        ),
        migrations.AddField(
            model_name='masterhabitat',
            name='biome_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter the biome code of the Master Habitat', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterhabitat',
            name='eco_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter the eco code of the Master Habitat', null=True),
        ),
        migrations.AlterField(
            model_name='masterhabitat',
            name='eco_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter the eco code of the Master Habitat', null=True),
        ),
    ]
