# Generated by Django 3.2.23 on 2024-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20240305_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietset',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score for the data', null=True),
        ),
        migrations.AddField(
            model_name='historicaldietset',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score for the data', null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score for the data', null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score for the data', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the group or category of the Master Habitat', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the group or category of the Master Habitat', max_length=250, null=True),
        ),
    ]
