# Generated by Django 3.2.19 on 2023-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0012_auto_20230523_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterattribute',
            name='source_attribute',
            field=models.ManyToManyField(through='mb.AttributeRelation', to='mb.SourceAttribute'),
        ),
        migrations.AddField(
            model_name='masterentity',
            name='source_entity',
            field=models.ManyToManyField(through='mb.EntityRelation', to='mb.SourceEntity'),
        ),
        migrations.AddField(
            model_name='masterunit',
            name='source_unit',
            field=models.ManyToManyField(to='mb.SourceUnit'),
        ),
        migrations.AddField(
            model_name='sourceattribute',
            name='master_attribute',
            field=models.ManyToManyField(through='mb.AttributeRelation', to='mb.MasterAttribute'),
        ),
        migrations.AddField(
            model_name='sourceentity',
            name='master_entity',
            field=models.ManyToManyField(through='mb.EntityRelation', to='mb.MasterEntity'),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='master_unit',
            field=models.ManyToManyField(through='mb.UnitRelation', to='mb.MasterUnit'),
        ),
    ]
