# Generated by Django 3.2.19 on 2023-06-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0013_auto_20230609_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterattribute',
            name='source_attribute',
        ),
        migrations.RemoveField(
            model_name='masterentity',
            name='source_entity',
        ),
        migrations.RemoveField(
            model_name='masterunit',
            name='source_unit',
        ),
        migrations.RemoveField(
            model_name='sourceattribute',
            name='master_attribute',
        ),
        migrations.RemoveField(
            model_name='sourceentity',
            name='master_entity',
        ),
        migrations.RemoveField(
            model_name='sourceunit',
            name='master_unit',
        ),
    ]
