# Generated by Django 3.2.23 on 2024-02-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0013_auto_20240214_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='tgn',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='tgn',
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='continent',
            field=models.CharField(blank=True, help_text='Enter the continent of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='countryCode',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='county',
            field=models.CharField(blank=True, help_text='Enter the county of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='geodeticDatum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='higherGeographyID',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locality',
            field=models.CharField(blank=True, help_text='Enter the locality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationAccordingTo',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationID',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationRemarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='municipality',
            field=models.CharField(blank=True, help_text='Enter the municipality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='stateProvince',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='continent',
            field=models.CharField(blank=True, help_text='Enter the continent of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='countryCode',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='county',
            field=models.CharField(blank=True, help_text='Enter the county of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='geodeticDatum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='higherGeographyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locality',
            field=models.CharField(blank=True, help_text='Enter the locality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationAccordingTo',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationID',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationRemarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='municipality',
            field=models.CharField(blank=True, help_text='Enter the municipality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='stateProvince',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
    ]
