# Generated by Django 3.2.23 on 2024-03-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0013_auto_20240214_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score calculated for the data', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='data_quality_score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Data quality score calculated for the data', max_length=3, null=True),
        ),
    ]
