# Generated by Django 3.2.23 on 2024-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0014_auto_20240214_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterhabitat',
            name='iiasa_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the IIASA code of the Master Habitat', null=True),
        ),
        migrations.AddField(
            model_name='masterhabitat',
            name='iiasa_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the IIASA code of the Master Habitat', null=True),
        ),
    ]
