# Generated by Django 3.2.19 on 2023-06-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0014_auto_20230615_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmasterattribute',
            old_name='remarks',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='masterattribute',
            old_name='remarks',
            new_name='description',
        ),
    ]
