# Generated by Django 3.2.23 on 2024-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0015_auto_20240214_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmasterhabitat',
            name='biome_code',
        ),
        migrations.RemoveField(
            model_name='historicalmasterhabitat',
            name='eco_code',
        ),
        migrations.RemoveField(
            model_name='historicalmasterhabitat',
            name='iiasa_code',
        ),
        migrations.RemoveField(
            model_name='masterhabitat',
            name='biome_code',
        ),
        migrations.RemoveField(
            model_name='masterhabitat',
            name='eco_code',
        ),
        migrations.RemoveField(
            model_name='masterhabitat',
            name='iiasa_code',
        ),
        migrations.AddField(
            model_name='historicalmasterhabitat',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the eco/biome/IIASA code of the Master Habitat', null=True),
        ),
        migrations.AddField(
            model_name='masterhabitat',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the eco/biome/IIASA code of the Master Habitat', null=True),
        ),
    ]
