# Generated by Django 3.2.19 on 2023-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0015_auto_20230622_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterattribute',
            name='max_allowed_value',
            field=models.CharField(blank=True, help_text='Enter maximum value for the Master Attribute', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterattribute',
            name='min_allowed_value',
            field=models.CharField(blank=True, help_text='Enter minimum value for the Master Attribute', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Master Attribute', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterattribute',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'numeric'), ('integer', 'integer'), ('categorical', 'categorical'), ('ordinal', 'ordinal'), ('logical', 'logical'), ('character', 'character')], default='character', help_text='Select the valueType of the MasterAttribute', max_length=25),
        ),
        migrations.AddField(
            model_name='masterattribute',
            name='max_allowed_value',
            field=models.CharField(blank=True, help_text='Enter maximum value for the Master Attribute', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='masterattribute',
            name='min_allowed_value',
            field=models.CharField(blank=True, help_text='Enter minimum value for the Master Attribute', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='masterattribute',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Master Attribute', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterattribute',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'numeric'), ('integer', 'integer'), ('categorical', 'categorical'), ('ordinal', 'ordinal'), ('logical', 'logical'), ('character', 'character')], default='character', help_text='Select the valueType of the MasterAttribute', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalmasterattribute',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description for the Master Attribute', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description for the Master Attribute', max_length=500, null=True),
        ),
    ]
