# Generated by Django 3.2.24 on 2024-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0016_auto_20240221_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the gourp or category of the Master Habitat', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the gourp or category of the Master Habitat', max_length=250, null=True),
        ),
    ]
