# Generated by Django 3.2.23 on 2024-02-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0017_auto_20240221_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterhabitat',
            name='source_habitat',
        ),
        migrations.RemoveField(
            model_name='sourcehabitat',
            name='master_habitat',
        ),
    ]
