# Generated by Django 3.2.19 on 2023-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0017_auto_20231215_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historicaldietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
