# Generated by Django 3.2.23 on 2024-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0018_auto_20231217_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterreference',
            name='is_public',
            field=models.BooleanField(help_text='Enter if the source is public', null=True),
        ),
        migrations.AddField(
            model_name='masterreference',
            name='is_public',
            field=models.BooleanField(help_text='Enter if the source is public', null=True),
        ),
    ]
