# Generated by Django 3.2.23 on 2024-02-07 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('tdwg', '0002_auto_20230512_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0018_auto_20231217_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('verbatim_event_date', models.CharField(blank=True, help_text='The verbatim original representation of the date and time information for an Event.', max_length=250, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_event', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_event', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalmasterreference',
            name='is_public',
            field=models.BooleanField(help_text='Enter if the source is public', null=True),
        ),
        migrations.AddField(
            model_name='historicalsourceentity',
            name='taxon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tdwg.taxon'),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinate system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_coordinates',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinates.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_depth',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim depth.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_eleveation',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim elevation.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_latitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim latitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_longitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim longitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_srs',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim spatial reference system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterreference',
            name='is_public',
            field=models.BooleanField(help_text='Enter if the source is public', null=True),
        ),
        migrations.AddField(
            model_name='sourceentity',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdwg.taxon'),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinate system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_coordinates',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinates.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_depth',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim depth.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_eleveation',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim elevation.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_latitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim latitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_longitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim longitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_srs',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim spatial reference system.', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='SourceHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('habitat_type', models.CharField(blank=True, help_text='Enter the Name of the Source Habitat', max_length=250, null=True)),
                ('habitat_percentage', models.CharField(blank=True, help_text='Enter the Percentage of the Source Habitat', max_length=250, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_sourcehabitat', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_sourcehabitat', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.sourcereference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('organism_quantity', models.CharField(blank=True, help_text='The number of organisms in the Occurrence.', max_length=50, null=True)),
                ('organism_quantity_type', models.CharField(blank=True, help_text='The type of the number of organisms in the Occurrence.', max_length=50, null=True)),
                ('occurrence_remarks', models.TextField(blank=True, help_text='Comments or notes about the Occurrence.', null=True)),
                ('associated_references', models.TextField(blank=True, help_text='References to other sources of information about the Occurrence.', null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_occurrence', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.event')),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_occurrence', to='mb.choicevalue')),
                ('life_stage', models.ForeignKey(blank=True, limit_choices_to={'choice_set': 'LifeStage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='life_stage_occurrence', to='mb.choicevalue')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_occurrence', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_occurrence', to='mb.sourceentity')),
                ('source_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcelocation')),
                ('source_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.sourcereference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSourceHabitat',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('habitat_type', models.CharField(blank=True, help_text='Enter the Name of the Source Habitat', max_length=250, null=True)),
                ('habitat_percentage', models.CharField(blank=True, help_text='Enter the Percentage of the Source Habitat', max_length=250, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcereference')),
            ],
            options={
                'verbose_name': 'historical source habitat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOccurrence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('organism_quantity', models.CharField(blank=True, help_text='The number of organisms in the Occurrence.', max_length=50, null=True)),
                ('organism_quantity_type', models.CharField(blank=True, help_text='The type of the number of organisms in the Occurrence.', max_length=50, null=True)),
                ('occurrence_remarks', models.TextField(blank=True, help_text='Comments or notes about the Occurrence.', null=True)),
                ('associated_references', models.TextField(blank=True, help_text='References to other sources of information about the Occurrence.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.event')),
                ('gender', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.choicevalue')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('life_stage', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'LifeStage'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.choicevalue')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourceentity')),
                ('source_location', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcelocation')),
                ('source_reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcereference')),
            ],
            options={
                'verbose_name': 'historical occurrence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('verbatim_event_date', models.CharField(blank=True, help_text='The verbatim original representation of the date and time information for an Event.', max_length=250, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_habitat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcehabitat')),
                ('source_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcemethod')),
            ],
            options={
                'verbose_name': 'historical event',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='source_habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcehabitat'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcemethod'),
        ),
    ]
