# Generated by Django 3.2.23 on 2024-02-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0018_auto_20240227_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsourcelocation',
            old_name='verbatim_eleveation',
            new_name='verbatim_elevation',
        ),
        migrations.RenameField(
            model_name='sourcelocation',
            old_name='verbatim_eleveation',
            new_name='verbatim_elevation',
        ),
    ]
