# Generated by Django 3.2.23 on 2024-01-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdwg', '0002_auto_20230512_1408'),
        ('mb', '0018_auto_20231217_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourceentity',
            name='scientific_name_authorship',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tdwg.taxon'),
        ),
        migrations.AddField(
            model_name='historicalsourceentity',
            name='taxon_rank',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tdwg.taxon'),
        ),
        migrations.AddField(
            model_name='sourceentity',
            name='scientific_name_authorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scientific_name_authorship_sourceentity', to='tdwg.taxon'),
        ),
        migrations.AddField(
            model_name='sourceentity',
            name='taxon_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='taxonrank_sourceentity', to='tdwg.taxon'),
        ),
    ]
