# Generated by Django 3.2.23 on 2024-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0019_auto_20240201_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloccurrence',
            name='verbatim_scientific_name',
            field=models.CharField(blank=True, help_text='Not a real!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='verbatim_scientific_name',
            field=models.CharField(blank=True, help_text='Not a real!', max_length=50, null=True),
        ),
    ]
