# Generated by Django 3.2.24 on 2024-02-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0019_auto_20240228_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='tgn',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='tgn',
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='continent',
            field=models.CharField(blank=True, help_text='Enter the continent of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='countryCode',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='county',
            field=models.CharField(blank=True, help_text='Enter the county of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='geodeticDatum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='higherGeographyID',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locality',
            field=models.CharField(blank=True, help_text='Enter the locality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationAccordingTo',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationID',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='locationRemarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='municipality',
            field=models.CharField(blank=True, help_text='Enter the municipality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='stateProvince',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='continent',
            field=models.CharField(blank=True, help_text='Enter the continent of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='countryCode',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='county',
            field=models.CharField(blank=True, help_text='Enter the county of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='geodeticDatum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='higherGeographyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locality',
            field=models.CharField(blank=True, help_text='Enter the locality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationAccordingTo',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationID',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='locationRemarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='municipality',
            field=models.CharField(blank=True, help_text='Enter the municipality of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='stateProvince',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLocationRelation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.masterlocation')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcelocation')),
            ],
            options={
                'verbose_name': 'historical location relation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_locationrelation', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('master_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.masterlocation')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_locationrelation', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.sourcelocation')),
            ],
            options={
                'unique_together': {('source_location', 'master_location')},
            },
        ),
    ]
