# Generated by Django 3.2.23 on 2024-02-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0019_auto_20240228_1508'),
        ('mb', '0019_auto_20240228_1625'),
    ]

    operations = [
    ]
