# Generated by Django 3.2.23 on 2024-02-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0019_auto_20240201_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.event'),
        ),
    ]
