# Generated by Django 3.2.25 on 2024-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0019_auto_20240403_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltimeperiod',
            name='name',
            field=models.CharField(help_text='Enter the Time Period', max_length=250),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='name',
            field=models.CharField(help_text='Enter the Time Period', max_length=250),
        ),
    ]
