# Generated by Django 3.2.23 on 2024-02-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0020_auto_20240202_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloccurrence',
            name='verbatim_scientific_name',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='verbatim_scientific_name',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.event'),
        ),
    ]
