# Generated by Django 3.2.25 on 2024-05-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0020_auto_20240422_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='decimalLatitude',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='decimalLongitude',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='geodeticDatum',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='higherGeographyID',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='locationAccordingTo',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='locationID',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='locationRemarks',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='maximumElevationInMeters',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='minimumElevationInMeters',
        ),
        migrations.RemoveField(
            model_name='historicalmasterlocation',
            name='stateProvince',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='decimalLatitude',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='decimalLongitude',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='geodeticDatum',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='higherGeographyID',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='locationAccordingTo',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='locationID',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='locationRemarks',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='maximumElevationInMeters',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='minimumElevationInMeters',
        ),
        migrations.RemoveField(
            model_name='masterlocation',
            name='stateProvince',
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='country_code',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimal_latitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='decimal_longitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='geodetic_datum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='higher_geography',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='Is this location a nature/wildlife/forest reserve?'),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='location_according_to',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='location_id',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='location_remarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='maximum_elevation_in_meters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='minimum_elevation_in_meters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlocation',
            name='state_province',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='match_attempts',
            field=models.IntegerField(default=0, help_text='The number of attempted matches for this location.'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='country_code',
            field=models.CharField(blank=True, help_text='Enter the country code of the Master Location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimal_latitude',
            field=models.CharField(blank=True, help_text='Enter the decimal latitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='decimal_longitude',
            field=models.CharField(blank=True, help_text='Enter the decimal longitude of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='geodetic_datum',
            field=models.CharField(blank=True, help_text='Enter the geodetic datum of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='higher_geography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.masterlocation'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='Is this location a nature/wildlife/forest reserve?'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='location_according_to',
            field=models.CharField(blank=True, help_text='Enter the information about the source of this location information of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='location_id',
            field=models.CharField(blank=True, help_text='Enter the locationID of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='location_remarks',
            field=models.CharField(blank=True, help_text='Enter the location remarks of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='maximum_elevation_in_meters',
            field=models.CharField(blank=True, help_text='Enter the maximum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='minimum_elevation_in_meters',
            field=models.CharField(blank=True, help_text='Enter the minimum elevation in meters of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='state_province',
            field=models.CharField(blank=True, help_text='Enter the state province of the Master Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='match_attempts',
            field=models.IntegerField(default=0, help_text='The number of attempted matches for this location.'),
        ),
        migrations.AlterField(
            model_name='masterlocation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.masterreference'),
        ),
        migrations.AlterField(
            model_name='sourcelocation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcereference'),
        ),
    ]
