# Generated by Django 3.2.23 on 2024-03-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0020_auto_20240229_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmasterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the group or category of the Master Habitat', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterhabitat',
            name='group',
            field=models.CharField(blank=True, help_text='Enter the group or category of the Master Habitat', max_length=250, null=True),
        ),
    ]
