# Generated by Django 3.2.23 on 2024-03-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0021_auto_20240307_1238'),
        ('mb', '0021_auto_20240307_1259'),
    ]

    operations = [
    ]
