# Generated by Django 3.2.24 on 2024-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0021_auto_20240313_1533'),
        ('mb', '0022_merge_0021_auto_20240307_1238_0021_auto_20240307_1259'),
    ]

    operations = [
    ]
