# Generated by Django 3.2.23 on 2024-02-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0022_alter_occurrence_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelocality',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sourcelocality',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sourcelocality',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='sourcelocality',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='historicaloccurrence',
            name='source_locality',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='source_locality',
        ),
        migrations.AddField(
            model_name='historicaloccurrence',
            name='source_location',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcelocation'),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinate system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_coordinates',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinates.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_depth',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim depth.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_eleveation',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim elevation.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_latitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim latitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_longitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim longitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcelocation',
            name='verbatim_srs',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim spatial reference system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='source_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcelocation'),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinate system.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_coordinates',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim coordinates.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_depth',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim depth.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_eleveation',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim elevation.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_latitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim latitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_longitude',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim longitude.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sourcelocation',
            name='verbatim_srs',
            field=models.CharField(blank=True, help_text='The original textual description of the verbatim spatial reference system.', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSourceLocality',
        ),
        migrations.DeleteModel(
            name='SourceLocality',
        ),
    ]
