# Generated by Django 3.2.24 on 2024-03-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0023_merge_20240314_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlocation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.masterreference'),
        ),
    ]
