# Generated by Django 5.2.2 on 2026-01-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mb", "0022_alter_historicalattributegrouprelation_options_and_more"),
        ("mb", "0024_alter_viewmastertraitvalue_table"),
    ]

    operations = []
