# Generated by Django 3.2.24 on 2024-03-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0024_alter_masterlocation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelocation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.sourcereference'),
        ),
    ]
