# Generated by Django 5.2.2 on 2026-01-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mb", "0022_alter_attributegrouprelation_created_by_and_more"),
        ("mb", "0026_merge_0023_alter_viewmastertraitvalue_table_0025_merge_0022_alter_historicalattributegrouprelation_options_and_more_0024_alter_viewmastertraitvalue_table"),
    ]

    operations = []
