# Generated by Django 3.2.24 on 2024-03-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0026_auto_20240328_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmasterlocation',
            old_name='higher_geography_id',
            new_name='higher_geography',
        ),
        migrations.RenameField(
            model_name='masterlocation',
            old_name='higher_geography_id',
            new_name='higher_geography',
        ),
    ]
