# Generated by Django 5.2.9 on 2026-01-13 15:12

import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0029_alter_attributegrouprelation_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegrouprelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributegrouprelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributerelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributerelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choicesetoptionrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choicesetoptionrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choicevalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choicevalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietset',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietset',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietsetitem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietsetitem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityclass',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityclass',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitatrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitatrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalattributegrouprelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalattributegrouprelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalattributerelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalattributerelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalchoicesetoptionrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalchoicesetoptionrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalchoicevalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalchoicevalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldietset',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldietset',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldietsetitem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldietsetitem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalentityclass',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalentityclass',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalentityrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalentityrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfooditem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfooditem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalhabitatrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalhabitatrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallocationrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallocationrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterattribute',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterattribute',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterattributegroup',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterattributegroup',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterchoicesetoption',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterchoicesetoption',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterentity',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterentity',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterhabitat',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterhabitat',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterlocation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterlocation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterunit',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmasterunit',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaloccurrence',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaloccurrence',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysis',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysis',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproximateanalysisitem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalreferencerelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalreferencerelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrelationclass',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrelationclass',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceattribute',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceattribute',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcechoicesetoption',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcechoicesetoption',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcechoicesetoptionvalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcechoicesetoptionvalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceentity',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceentity',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcehabitat',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcehabitat',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcelocation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcelocation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcemeasurementvalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcemethod',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcemethod',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcereference',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcereference',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcestatistic',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourcestatistic',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceunit',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsourceunit',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltimeperiod',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltimeperiod',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalunitconversion',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalunitconversion',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalunitrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalunitrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattributegroup',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattributegroup',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterchoicesetoption',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterchoicesetoption',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterentity',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterentity',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterhabitat',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterhabitat',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterlocation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterlocation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterunit',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterunit',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proximateanalysis',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proximateanalysis',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proximateanalysisitem',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencerelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencerelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationclass',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationclass',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceattribute',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceattribute',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoption',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoption',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoptionvalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcechoicesetoptionvalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceentity',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceentity',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcehabitat',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcehabitat',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcelocation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcelocation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcemethod',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcemethod',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcestatistic',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourcestatistic',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceunit',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceunit',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitrelation',
            name='created_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitrelation',
            name='modified_by',
            field=utils.fields.AutoUserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
