name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    services:
      mysql:
        image: maridb
        env:
          DB_HOST: db
          DB_PORT: 3306
          DB_NAME: django_tm
          DB_USER: django_tm
          DB_PASSWORD: password
          DJANGO_ALLOWED_HOSTS: web,127.0.0.1, localhost
        options:
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./app
    - name: Run Tests
      env:
        DB_HOST: db
        DB_PORT: 3306
        DB_NAME: django_tm
        DB_USER: django_tm
        DB_PASSWORD: password
        DJANGO_ALLOWED_HOSTS: web,127.0.0.1, localhost
      run: |
        python ./app/manage.py test imports
