name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v2

