# Generated by Django 3.2.12 on 2022-06-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourceattribute',
            name='method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.sourcemethod'),
        ),
        migrations.AddField(
            model_name='sourceattribute',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_sourceattribute', to='mb.sourcemethod'),
        ),
    ]
