# Generated by Django 3.2.12 on 2022-06-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0004_auto_20220614_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='life_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'LifeStage'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.choicevalue'),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='measured_by',
            field=models.TextField(blank=True, help_text="A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the measurement. The recommended best practice is to separate the values with a vertical bar (' | ').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcemeasurementvalue',
            name='measurement_accuracy',
            field=models.TextField(blank=True, help_text='The description of the potential error associated with the measurementValue.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='life_stage',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_set': 'LifeStage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifestagesourcemeasurementvalue', to='mb.choicevalue'),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='measured_by',
            field=models.TextField(blank=True, help_text="A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the measurement. The recommended best practice is to separate the values with a vertical bar (' | ').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourcemeasurementvalue',
            name='measurement_accuracy',
            field=models.TextField(blank=True, help_text='The description of the potential error associated with the measurementValue.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemeasurementvalue',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_set': 'Gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gendersourcemeasurementvalue', to='mb.choicevalue'),
        ),
    ]
