# Generated by Django 3.2.15 on 2023-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0008_auto_20230214_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historicaldietsetitem',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
